const nodemailer = require('nodemailer');

/**
 * Sends an email notification to the administrator when a new chatbot query is submitted.
 * Falls back to console logging if SMTP environment variables are not configured.
 * @param {Object} query - The query document containing name, email, phone, productName, productId, message, and createdAt.
 */
const sendQueryNotification = async (query) => {
  try {
    const smtpHost = process.env.SMTP_HOST;
    const smtpPort = process.env.SMTP_PORT || 587;
    const smtpUser = process.env.SMTP_USER;
    const smtpPass = process.env.SMTP_PASS;
    const smtpFrom = process.env.SMTP_FROM || smtpUser || 'no-reply@trivantas.com';
    const notificationEmail = process.env.NOTIFICATION_EMAIL || process.env.ADMIN_EMAIL || 'admin@trivantas.com';

    // If SMTP is not fully configured, fall back to console logging
    if (!smtpHost || !smtpUser || !smtpPass) {
      console.log('------------------------------------------------------------');
      console.log('[EMAIL] WARNING: SMTP is not configured. Notification Details:');
      console.log(`To:            ${notificationEmail}`);
      console.log(`Customer Name: ${query.name}`);
      console.log(`Email Address: ${query.email}`);
      console.log(`Phone Number:  ${query.phone}`);
      console.log(`Product Name:  ${query.productName} (${query.productId})`);
      console.log(`Message:       ${query.message}`);
      console.log('------------------------------------------------------------');
      return;
    }

    const transporter = nodemailer.createTransport({
      host: smtpHost,
      port: Number(smtpPort),
      secure: Number(smtpPort) === 465, // true for 465, false for other ports (like 587)
      auth: {
        user: smtpUser,
        pass: smtpPass,
      },
    });

    const mailOptions = {
      from: `"${query.name} via Chatbot" <${smtpFrom}>`,
      to: notificationEmail,
      replyTo: query.email,
      subject: `New Chatbot Query - ${query.productName}`,
      html: `
        <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden;">
          <div style="background-color: #1e3a8a; padding: 20px; text-align: center; color: white;">
            <h2 style="margin: 0; font-size: 24px;">New Chatbot Query Received</h2>
          </div>
          <div style="padding: 20px;">
            <p>Hello Admin,</p>
            <p>A new customer query has been submitted through the Trivantas Chatbot. Here are the details:</p>
            
            <table style="width: 100%; border-collapse: collapse; margin-top: 15px; margin-bottom: 15px;">
              <tr style="border-bottom: 1px solid #eee;">
                <td style="padding: 8px; font-weight: bold; width: 30%;">Customer Name:</td>
                <td style="padding: 8px;">${query.name}</td>
              </tr>
              <tr style="border-bottom: 1px solid #eee;">
                <td style="padding: 8px; font-weight: bold;">Email Address:</td>
                <td style="padding: 8px;"><a href="mailto:${query.email}">${query.email}</a></td>
              </tr>
              <tr style="border-bottom: 1px solid #eee;">
                <td style="padding: 8px; font-weight: bold;">Phone Number:</td>
                <td style="padding: 8px;"><a href="tel:${query.phone}">${query.phone}</a></td>
              </tr>
              <tr style="border-bottom: 1px solid #eee;">
                <td style="padding: 8px; font-weight: bold;">Product:</td>
                <td style="padding: 8px;">${query.productName} (ID: ${query.productId})</td>
              </tr>
              <tr style="border-bottom: 1px solid #eee;">
                <td style="padding: 8px; font-weight: bold;">Submitted At:</td>
                <td style="padding: 8px;">${new Date(query.createdAt).toLocaleString()}</td>
              </tr>
            </table>

            <div style="background-color: #f9fafb; border-left: 4px solid #1e3a8a; padding: 15px; margin-top: 20px;">
              <h4 style="margin: 0 0 10px 0; color: #1e3a8a;">Message / Query:</h4>
              <p style="margin: 0; font-style: italic; white-space: pre-wrap;">${query.message}</p>
            </div>
            
            <p style="margin-top: 25px;">You can view and manage this query directly in the <a href="${process.env.FRONTEND_URL || 'http://localhost:5173'}/admin" style="color: #1e3a8a; text-decoration: underline;">Admin Dashboard</a>.</p>
          </div>
          <div style="background-color: #f3f4f6; padding: 15px; text-align: center; font-size: 12px; color: #6b7280; border-top: 1px solid #e0e0e0;">
            This email was automatically generated by the Trivantas Chatbot system.
          </div>
        </div>
      `,
    };

    const info = await transporter.sendMail(mailOptions);
    console.log(`[EMAIL] Query notification email sent: ${info.messageId}`);
    return info;
  } catch (error) {
    console.error('[EMAIL] Failed to send query notification email:', error);
  }
};

module.exports = {
  sendQueryNotification,
};
